---
- name:              Cleanup Binaries directory
  file:              path={{ __tmp_dir }} state=absent
  when:              version_already_installed.rc != 0
  ignore_errors:     true

- name:              Create Binaries directory
  file:              path={{ __tmp_dir }} state=directory mode=0755
  when:              version_already_installed.rc != 0

- name:              Create Logs directory
  file:              path={{ __logs_dir }} state=directory mode=0755
  when:              version_already_installed.rc != 0

#- name:              Download WAS Fixes
#  get_url:
#    url:             "{{ was_repository_url }}/{{ item.file_name }}"
#    dest:            "{{ __tmp_dir }}/{{ item.file_name }}"
#    mode:            0755
#    checksum:        sha256:{{ item.check_sum }}
#  with_items:        "{{ __this_files }}"
#  when:              version_already_installed.rc != 0

- name:              Download WAS Fixes
  copy:
    src:             "{{ was_packages }}/was/{{ item.file_name }}"
    dest:            "{{ __tmp_dir }}/{{ item.file_name }}"
    mode:            0755
  with_items:        "{{ __this_files }}"
  when:              version_already_installed.rc != 0

- name:              Extract WAS Fixes
  unarchive:
    src:             "{{ __tmp_dir }}/{{ item.file_name }}"
    dest:            "{{ __tmp_dir }}/"
    copy:            no
  with_items:        "{{ __this_files }}"
  when:              version_already_installed.rc != 0

- name:              Generate WAS Response file
  template:
    src:             "{{ __tpl_file }}"
    dest:            "{{ __rsp_file }}"
  when:              version_already_installed.rc != 0

- name:              Disable Repository on Installation Manager
  replace:
    path:            /var/ibm/InstallationManager/.settings/com.ibm.cic.agent.core.prefs
    regexp:          '(\s*)RepositoryIsOpen=true(\s*)'
    replace:         '\1RepositoryIsOpen=false\2'
    backup:          yes
  ignore_errors:     true

- name:              Install IBM WAS ND Fixes Software
  command:
    chdir={{ __tmp_dir }}
    {{ __iim_install_location }}/eclipse/tools/imcl -acceptLicense -sVP -log {{ __log_file }} input {{ __rsp_file }}
  register:          cout
  changed_when:      ( cout.stdout.find(__version_check) != -1)
  when:              version_already_installed.rc != 0

#- debug:            var=cout

- name:              Cleanup Binaries directory
  file:
    state:           absent
    path:            "{{ __tmp_dir }}"
  when:              version_already_installed.rc != 0
