# Install WebSphere Application Server - Network Deployment
#
# Variables used in this playbook that can be setup at hosts file.
#
# HTTP server that has installation Files
#   was_repository_url:    http://192.168.1.1/was/8.5.5
#
# How to Run
#

# ansible-playbook -i environments/hosts.development -u <username> -k playbooks/ibm-was-nd-complete.yml
---
- name:                    Install WebSphere Application Server - Network Deployment
  hosts:                   dmgr,was-servers
  become:                  true
  roles:
    - roles/installation-manager-install
    - roles/was-nd-install
    - roles/was-nd-fix-install
    - roles/was-java-install
  vars:
    #tmp_dir:              "/opt/IBM/Binaries/was"
    #iim_install_location: "/opt/IBM/InstallationManager"
    #was_install_location: "/opt/IBM/WebSphere/AppServer"
    #imshared_location:    "/opt/IBM/IMShared"

    #was_version:          "8.5.5000.20130514_1044"
    #was_files:
    #  - { file_name: WAS_ND_V8.5.5_1_OF_3.zip, check_sum: b1333962ba4b25c8632c7e4c82b472350337e99febac8f70ffbd551ca3905e83 }
    #  - { file_name: WAS_ND_V8.5.5_2_OF_3.zip, check_sum: 440b7ed82089d43b1d45c1e908bf0a1951fed98f2542b6d37c8b5e7274c6b1c9 }
    #  - { file_name: WAS_ND_V8.5.5_3_OF_3.zip, check_sum: b73ae070656bed6399a113c2db9fb0abaf5505b0d41c564bf2a58ce0b1e0dcd2 }

    #was_fp_version:       "8.5.5011.20161206_1434"
    #was_fp_files:
    #  - { file_name: 8.5.5-WS-WAS-FP011-part1.zip, check_sum: bd9b51bd6a8522da8a6a19fcb0cf0ccc9980b13f5da2a1bcd4db2242ae555a66 }
    #  - { file_name: 8.5.5-WS-WAS-FP011-part2.zip, check_sum: 0ab936b38ebee485471ce9f6fdbf5c0a609f0ffa837247fb81db6935f5cc061c }

    #was_fp_version:       "8.5.5009.20160225_0435"
    #was_fp_files:
    #  - { file_name: 8.5.5-WS-WAS-FP0000009-part1.zip, check_sum: bf0817f50472c7f1ad0c50863ff0e7a07fb73f69f09a60bfad798d2b3cc1e3ae }
    #  - { file_name: 8.5.5-WS-WAS-FP0000009-part2.zip, check_sum: c5501a75da3ab78887fa0208f26d7d81517e39a0c7e184bf36d28fbc93acbe22 }

    #was_java_version:     "8.0.2010.20160224_1829"
    #was_java_files:
    #  - { file_name: 8.0.2.10-WS-IBMWASJAVA-Linux.zip, check_sum: 7338d90d760596d95eb9622aa6a5ceb21c5604cece702abeeb8565c331f2aaa1 }
