---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include overrides specific to RHEL 7.
  include_vars: RedHat-7.yml
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == "7"

- name: Include overrides specific to Fedora.
  include_vars: Fedora.yml
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution == "Fedora"

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure directories to mount exist
  file: 'path="{{ item.client_path }}" state=directory'
  with_items: "{{ mount_pointers }}"

- name: Mount client path to NFS server.
  mount:
    src: "{{ item.nfs_host }}:{{ item.nfs_path }}"
    name: "{{ item.client_path }}"
    fstype: nfs
    state: mounted
  with_items: "{{ mount_pointers }}"
