# How to Run
#
# ansible-playbook -i hosts.development -k ansible-ibm-websphere/playbooks/was-dmgr-create-profile.yml
#
---
- name:                     DeleteAll WAS Profile
  hosts:                    dmgr,was-servers
  become:                   true
  vars:
    #__profile_name:         "{{ profile_name | default('AppSrv01') }}"
    #__was_install_location: "{{ was_install_location  | default('/opt/IBM/WebSphere/AppServer') }}"
  roles:
    - was-profile-delete-all
