---
tomcat_default_service_template: "{{ tomcat_server_sysvinit_template }}"
tomcat_default_service_file: "tomcat_%s"
tomcat_default_service_name: "tomcat_%s"
tomcat_service_dir: /etc/init.d
tomcat_service_file_mode: 755
