- name: Create Related Dockerdd Directory
  file: path={{ DEFAULT_WORKSPACE }}/docker/ state=directory

- name: Copy paas_basic_pipeline Container Related File(1/1)
  template: src=paas_basic_pipeline.j2 dest={{ DEFAULT_WORKSPACE }}/docker/paas_basic_pipeline.sh mode=0755

- name: Start paas_basic_pipeline Container Instance
  shell: "{{ DEFAULT_WORKSPACE }}/docker/paas_basic_pipeline.sh"
