---
sudoer_aliases: {}
sudoer_specs: []
sudoer_defaults:
#  - requiretty
  - "!visiblepw"
  - always_set_home
  - env_reset
  - env_keep:
    - COLORS
    - DISPLAY
    - HOSTNAME
    - HISTSIZE
    - INPUTRC
    - KDEDIR
    - LS_COLORS
    - MAIL
    - PS1
    - PS2
    - QTDIR
    - USERNAME
    - LANG
    - LC_ADDRESS
    - LC_CTYPE
    - LC_COLLATE
    - LC_IDENTIFICATION
    - LC_MEASUREMENT
    - LC_MESSAGES
    - LC_MONETARY
    - LC_NAME
    - LC_NUMERIC
    - LC_PAPER
    - LC_TELEPHONE
    - LC_TIME
    - LC_ALL
    - LANGUAGE
    - LINGUAS
    - _XKB_CHARSET
    - XAUTHORITY
  - secure_path: /sbin:/bin:/usr/sbin:/usr/bin
sudoer_separate_specs: True
sudoer_rewrite_sudoers_file: False
sudoer_remove_unauthorized_specs: False
# whether or not remove sudo privilege
sudoer_remove_special_specs: False

operate_type: add

sudoer_group: "{% if ansible_os_family == 'AIX' %}security{% else %}root{% endif %}"
