---
- name: Systemd script.
  template: src=zookeeper.service.j2 dest=/lib/systemd/system/zookeeper.service
  when: ansible_service_mgr == 'systemd'

- name: enable zookeeper service
  service:
    name: zookeeper
    enabled: yes
  when: ansible_service_mgr == 'systemd'
  notify:
    - Reload systemctl daemon
    - Restart zookeeper
