---
# Script for fetching Java Cryptography Extensions (JCE)

#- name: get JCE
#  get_url:
#    url:     "{{ jce_zip_url }}"
#    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
#    dest:    "{{ java_download_path }}/{{ jce_zip_file }}"

- name: get JCE
  copy:
    src: "{{ packages_dir }}/oracle_java/{{ jce_zip_file }}"
    dest: "{{ java_download_path }}/{{ jce_zip_file }}"
    
