# Lab playbook - sets up the host specific shit
---

  epel_rpm: "{% if ansible_distribution_major_version|int==6%}{{ epel6_rpm }}{%elif ansible_distribution_major_version|int==7 %}{{ epel7_rpm }}{% else %}None{% endif %}"
  epel7_rpm: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  epel6_rpm: https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
  ol_repo_file: "{% if ansible_distribution_major_version|int==6%}{{ ol6_repo_file }}{%elif ansible_distribution_major_version|int==7 %}{{ ol7_repo_file }}{% else %}None{% endif %}"
  ol6_repo_file: public-yum-ol6.repo
  ol7_repo_file: public-yum-ol7.repo
  repo_dir: /etc/yum.repos.d/
#  default_user: ansible
  install_os_packages: true
  configure_epel_repo: false
  configure_public_yum_repo: false
  configure_motd: true
  configure_ntp: false
  common_packages: "{% if ansible_distribution_major_version|int==6%}{{ common_packages_el6 }}{%elif ansible_distribution_major_version|int==7 %}{{ common_packages_el7 }}{% else %}None{% endif %}"
  common_packages_el6:
      - screen
      - facter
      - procps
      - module-init-tools
      - ethtool
      - bc
      - nc
      - bind-utils
      - nfs-utils
      - make
      - sysstat
      - unzip
      - openssh-clients
      - compat-libcap1
      - collectl
      - rlwrap
      - tigervnc-server
      - ntp
      - expect
      - git
      - lvm2
      - xfsprogs
      - btrfs-progs
      - tmux
      - python-devel
      - python-pip
      - libselinux-python
      - twm
      - autofs
      - parted
      - mlocate
      - ntp
      - ksh
      #- mksh
      - lvm2
      - xfsprogs
      - btrfs-progs
      - procps
      - psmisc
      
  common_packages_el7:
      - screen
      - facter
      - procps
      - module-init-tools
      - ethtool
      - bc
      - nc
      - bind-utils
      - nfs-utils
      - make
      - sysstat
      - unzip
      - openssh-clients
      - compat-libcap1
      - collectl
      - rlwrap
      - tigervnc-server
      - ntp
      - expect
      - git
      - lvm2
      - xfsprogs
      - btrfs-progs
      - python-devel
      - python-pip
      - libselinux-python
      - autofs
      - parted
      - mlocate
      - ntp
      - ksh
      #- mksh
      - lvm2
      - xfsprogs
      - btrfs-progs
      - procps
      - psmisc
      
  common_packages_sles:
      - screen
#      - facter
      - procps
      - module-init-tools
      - ethtool
      - bc
#      - nc
      - bind-utils
#      - nfs-utils
      - make
      - sysstat
      - unzip
#      - openssh-clients
#      - compat-libcap1
#      - twm
#      - collectl
#      - rlwrap
#      - tigervnc-server
      - ntp
      - expect
#      - git
      - lvm2
#      - xfsprogs
#      - btrfs-progs
#      - tmux
#      - python-devel
#      - python-pip
#      - libselinux-python
      - autofs
