---
# defaults file for activemq-ansible-role
amq_user: activemq
amq_group:  activemq
amq_install_dir: /opt
amq_conf_dir: '{{ amq_install_dir }}/activemq/conf'
amq_run_dir: "/opt/{{ amq_user }}"
amq_home_dir:  /var/lib/activemq
amq_log_dir: /var/log/activemq

# default installation mode
amq_install_mode: tarball
amq_skip_checksum: true

# calculate version
amq_version_major: "5"
amq_version_minor: "13"
amq_version_patch: "3"

amq_version: "{{ amq_version_major }}.{{ amq_version_minor }}.{{ amq_version_patch }}"

# Let's put all supported versions chacksum here in order to validate them if they appear
amq_checksums:
  - { version: "5.10.0", checksum: "md5:3005575267b0005c2eeb32a23a945e39" }

amq_package: "{{ packages_dir }}/activemq/apache-activemq-{{ amq_version }}-bin.tar.gz"

amq_env_vars:
  ACTIVEMQ_USER: "{{ amq_user }}"
  ACTIVEMQ_BASE: "{{ amq_run_dir }}"

# Use custom broker xml config
activemq_custom_xml_config: True
activemq_custom_xml_config_path: 'activemq.xml.j2'

# activemq broker config
activemq_openwire_transport_connector_uri: 'tcp://0.0.0.0:61616?maximumConnections=1000&amp;wireformat.maxFrameSize=104857600'
activemq_amqp_transport_connector_uri: 'amqp://0.0.0.0:5672?maximumConnections=1000&amp;wireformat.maxFrameSize=104857600'
activemq_stomp_transport_connector_uri: 'stomp://0.0.0.0:61713?transport.closeAsync=false'
activemq_stomp_and_nio_transport_connector_uri: 'stomp+nio://0.0.0.0:61712?transport.closeAsync=false'
