- name: Create Related Dockerdd Directory
  file: path={{ DEFAULT_WORKSPACE }}/docker/ state=directory

- name: Copy paas_data_authority Container Related File(1/1)
  template: src=paas_data_authority.j2 dest={{ DEFAULT_WORKSPACE }}/docker/paas_data_authority.sh mode=0755

- name: Start paas_data_authority Container Instance
  shell: "{{ DEFAULT_WORKSPACE }}/docker/paas_data_authority.sh"
