---
- name: restart consul on Linux
  service:
    name: consul
    state: restarted
  when: ansible_os_family != "Windows"
  listen: 'restart consul'

- name: restart consul on Windows
  win_nssm:
    name: consul
    state: restarted
  when: ansible_os_family == "Windows"
  listen: 'restart consul'
