---
- name: start consul on Linux
  service:
    name: consul
    state: started
  when: ansible_os_family != "Windows"
  listen: 'start consul'

- name: start consul on Windows
  win_nssm:
    name: consul
    state: started
  when: ansible_os_family == "Windows"
  listen: 'start consul'