- name: "create dir"
  file:
    path: /var/opt/jfrog/artifactory
    mode: '0777'
    state: directory

- name: Create Related Dockerdd Directory
  file: path={{ DEFAULT_WORKSPACE }}/docker/ state=directory

- name: Copy paas_artifactory Container Related File(1/1)
  template: src=paas_artifactory.j2 dest={{ DEFAULT_WORKSPACE }}/docker/docker_artifactory.sh mode=0755  

- name: Start paas_artifactory Container Instance
  shell: "{{ DEFAULT_WORKSPACE }}/docker/docker_artifactory.sh"
