---

- name: install-home-gi | Extract files to stage-area (GI)
  unarchive:
       src={{ oracle_stage_remote }}/{{ item.filename }}
       dest={{ oracle_stage }}/{{ item.version }}
       copy=no
       creates={{ oracle_stage }}/{{ item.version }}/{{ item.creates}}
  with_items: "{{oracle_sw_image_gi}}"
  become: yes
  become_user: "{{ grid_install_user }}"
  tags:
    - oragridswunpack
  when: oracle_home_gi not in checkgiinstall.stdout and oracle_install_version_gi  == item.version and oracle_sw_copy and oracle_sw_unpack

- name: install-home-gi | Extract files to stage-area (GI) (from remote location)
  unarchive:
       src={{ oracle_stage_remote }}/{{ item.filename }}
       dest={{ oracle_stage }}/{{ item.version }}
       copy=no
       creates={{ oracle_stage }}/{{ item.version }}/{{ item.creates}}
  with_items: "{{oracle_sw_image_gi}}"
  become: yes
  become_user: "{{ grid_install_user }}"
  tags:
  - oragridswunpack
  when: oracle_home_gi not in checkgiinstall.stdout and oracle_install_version_gi == item.version and not oracle_sw_copy and oracle_sw_unpack

- name: install-home-gi | Install cvuqdisk rpm
  yum: name="{{ oracle_stage_install }}/{{ oracle_install_version_gi }}/grid/rpm/{{ cvuqdisk_rpm }}" state=present
  when: configure_cluster
  tags: cvuqdisk
  ignore_errors: true

- name: install-home-gi | Setup response file for install (GI)
  template: src=grid-install.rsp.{{ oracle_install_version_gi }}.j2 dest={{ oracle_rsp_stage }}/{{ oracle_grid_responsefile }} owner="{{ grid_install_user }}" group={{ oracle_group }} mode=600 backup=yes
  with_items: "{{asm_diskgroups}}"
  run_once: "{{ configure_cluster}}"
  tags:
    - responsefilegi
  when: oracle_home_gi not in checkgiinstall.stdout and item.diskgroup == oracle_asm_init_dg

- name: install-home-gi | Install Grid Infrastructure
  shell: "{{ oracle_stage_install }}/{{ oracle_install_version_gi }}/grid/runInstaller -responseFile {{ oracle_rsp_stage }}/{{ oracle_grid_responsefile }} -waitforcompletion -ignorePrereq -ignoreSysPrereqs -showProgress -silent"
  become: yes
  become_user: "{{ grid_install_user }}"
  run_once: "{{ configure_cluster}}"
  tags:
    - oragridinstall
  when: oracle_home_gi not in checkgiinstall.stdout #and oracle_sw_unpack
  register: giinstall

- debug: var=giinstall.stdout_lines
  run_once: "{{ configure_cluster}}"
  when: oracle_home_gi not in checkgiinstall.stdout

- include_role:
        name: oraswgi-manage-patches
  when: patch_before_rootsh and apply_patches_gi

- name: install-home-gi | Run oraInstroot script after installation
  shell: "{{ oracle_inventory_loc }}/orainstRoot.sh"
  become: yes
  tags:
    - runroot
  when: oracle_home_gi not in checkgiinstall.stdout

# ray tan add 
#- name: Fix root.sh run failed because of init.d replaced by systemd
#  tasks:
- name: check if ohas.service exists.
  shell: ls /usr/lib/systemd/system/ohas.service
  ignore_errors: True
  register: ohas_exists
- name: Create ohas service file
  file: path=/usr/lib/systemd/system/ohas.service state=touch mode=777
  when: ohas_exists is failed
- name: Add content to ohas.service
  blockinfile: path=/usr/lib/systemd/system/ohas.service block="[Unit]\nDescription=Oracle High Availability Services\nAfter=syslog.target\n\n[Service]\nExecStart=/etc/init.d/init.ohasd run >/dev/null 2>&1 Type=simple\nRestart=always\nRestartSec=10\nStartLimitInterval=0\n\n[Install]\nWantedBy=multi-user.target" marker="#{mark} create by ansible"
  when: ohas_exists is failed
- name: enable and start ohas.service
  systemd: state=started name=ohas.service enabled=yes
  when: ohas_exists is failed

- name: install-home-gi | Run root script after installation (Master Node)
  shell: "{{ oracle_home_gi }}/root.sh"
  become: yes
  run_once: "{{ configure_cluster}}"
  tags:
    - runroot
  when: oracle_home_gi not in checkgiinstall.stdout
  register: rootmaster

- debug: var=rootmaster.stdout_lines
  run_once: "{{ configure_cluster}}"
  when: oracle_home_gi not in checkgiinstall.stdout

- debug: var=groups[hostgroup]

- debug: var=checkgiinstall.stdout

- debug: var=oracle_home_gi

- debug: var=inventory_hostname

- debug: var=cluster_master

- debug: var=configure_cluster

- name: install-home-gi | Run root script after installation (Other Nodes)
  shell: "sleep {{ item.0 * 60 }}; {{ oracle_home_gi }}/root.sh"
  become: yes
  with_indexed_items: "{{groups[hostgroup]}}"
  tags:
    - runroot
  #when: oracle_home_gi not in checkgiinstall.stdout  and inventory_hostname == item.1
  when: configure_cluster and inventory_hostname != cluster_master and inventory_hostname == item.1 and oracle_home_gi not in checkgiinstall.stdout
  register: rootother

- debug: var=rootother.stdout_lines
  #when: not master_node and oracle_home_gi not in checkgiinstall.stdout
  when: configure_cluster and inventory_hostname != cluster_master and oracle_home_gi not in checkgiinstall.stdout
  ignore_errors: True

- name: install-home-gi | Setup response file for configToolAllCommands
  template: src=configtoolallcommands.rsp.{{ oracle_install_version_gi }}.j2 dest={{ oracle_rsp_stage }}/configtoolallcommands.rsp owner="{{ grid_install_user }}" group={{ oracle_group }} mode=755 backup=yes
  run_once: "{{ configure_cluster}}"
  tags:
    - responsefileconfigtool
  when: run_configtoolallcommand  and oracle_home_gi not in checkgiinstall.stdout

- name: install-home-gi | Run configToolAllCommands
  shell: "{{ oracle_home_gi }}/cfgtoollogs/configToolAllCommands RESPONSE_FILE={{ oracle_rsp_stage }}/configtoolallcommands.rsp"
  become: yes
  become_user: "{{ grid_install_user }}"
  run_once: "{{ configure_cluster}}"
  tags:
    - runconfigtool
  when: run_configtoolallcommand and oracle_home_gi not in checkgiinstall.stdout
  ignore_errors: true
  register: configtool
