---

- name: prepare installation
  hosts: {{ ip_list }}
  vars:
    yum_baseurl: "{{ bocloud_ansible.packages_yum_baseurl }}"
    backup_repo: True
    restory_repo: False
  roles:
    - role: bocloud_common

- hosts: {{ ip_list }}
  vars: 
    java_version: 8
    java_subversion: 161
    packages_dir: "{{ bocloud_ansible.packages_path }}"
    java_download_from_oracle: False
    java_set_javahome: True
    java_depended: True
    zookeeper_version: {{ args.version }}
    zookeeper_tarball: {{ bocloud_ansible.packages_path }}/zookeeper/zookeeper-{{ args.version }}.tar.gz
    {%- if args.software_config is defined %}
    zookeeper_cluster_ports: "{{ args.software_config.switch_port|default('2888') }}:{{ args.software_config.choice_port|default('3888') }}"
    {%- endif %}
    {%- if args.software_config is defined %}
    {%- for key, value in args.software_config.iteritems() %}
    {{ key }}: "{{ value }}"
    {%- endfor %}
    {%- endif %}

  roles:
    - role: ansible-oracle-java
    - role: ansible-zookeeper
      {%- if args.cluster_install %}
      zookeeper_hosts:
      {%- for ip in ip_list %}
        - host: {{ ip }}
          id: {{ loop.index }}
      {%- endfor %}
      {%- endif %}

- name: restory original environment
  hosts: {{ ip_list }}
  vars:
    backup_repo: False
    restory_repo: True
    configure_bocloud_repo: False
  roles:
    - role: bocloud_common