---

- name: prepare installation
  hosts: {{ ip_list }}
  vars:
    yum_baseurl: "{{ bocloud_ansible.packages_yum_baseurl }}"
    backup_repo: True
    restory_repo: False
  roles:
    - role: bocloud_common

- hosts: {{ ip_list }}
  vars:
    java_version: {{ args.version.split('u')[0] }}
    java_subversion: {{ args.version.split('u')[1] }}
    packages_dir: {{ bocloud_ansible.packages_path }}
    java_download_from_oracle: False
    {%- if args.set_java_home is defined %}
    java_set_javahome: {{ args.set_java_home }}
    {%- endif %}
    {%- if args.install_jce is defined %}
    java_install_jce: {{ args.install_jce }}
    {%- endif %}

  roles:
    - role: ansible-oracle-java

- name: restory original environment
  hosts: {{ ip_list }}
  vars:
    backup_repo: False
    restory_repo: True
    configure_bocloud_repo: False
  roles:
    - role: bocloud_common