---

- name: prepare installation
  hosts: {{ ip_list }}
  vars:
    yum_baseurl: "{{ bocloud_ansible.packages_yum_baseurl }}"
    backup_repo: True
    restory_repo: False
  roles:
    - role: bocloud_common

- hosts: {{ ip_list }}
  vars:
    java_version: 8
    java_subversion: 161
    packages_dir: "{{ bocloud_ansible.packages_path }}"
    java_download_from_oracle: False
    java_set_javahome: True
    java_depended: True
    tomcat_version: {{ args.version }}
    tomcat_tarball_dir: {{ bocloud_ansible.packages_path }}/tomcat/
    tomcat_path_to_lib_role: {{ bocloud_ansible.playbook_roles }}
    {%- if args.software_config is defined %}
    {%- for key, value in args.software_config.iteritems() %}
    {{ key }}: {{ value }}
    {%- endfor %}
    {%- endif %}
    {%- if args.tomcat_instances is defined %}
    tomcat_instances:
    {%- for instance in args.tomcat_instances %}
      - {{ instance }}
    {%- endfor %}
    {%- endif %}

  roles:
    - role: ansible-oracle-java
    - role: ansible-tomcat

- name: restory original environment
  hosts: {{ ip_list }}
  vars:
    backup_repo: False
    restory_repo: True
    configure_bocloud_repo: False
  roles:
    - role: bocloud_common

