---

- name: prepare installation
  hosts: {{ ip_list }}
  vars:
    yum_baseurl: "{{ bocloud_ansible.packages_yum_baseurl }}"
    backup_repo: True
    restory_repo: False
  roles:
    - role: bocloud_common

- name: install etcd
  hosts: {{ ip_list }}
  vars:
    packages_dir: "{{ bocloud_ansible.packages_path }}"
    etcd_version: "{{ args.version }}"
    etcd_votes_list: {{ ip_list }}
    {%- for key, value in args.software_config.iteritems() %}
    {{ key }}: {{ value }}
    {%- endfor %}
    {%- if args.etcd_initial_cluster_token is defined %}
    etcd_initial_cluster_token: "{{ args.etcd_initial_cluster_token }}"
    {%- endif %}
    {%- if args.etcd_secure is defined %}
    etcd_secure: {{ args.etcd_secure }}
    {%- endif %}
    {%- if args.cluster_install is defined %}
    etcd_cluster_install: {{ args.cluster_install }}
    {%- endif %}
  roles:
    - role: ansible-etcd

- name: restory original environment
  hosts: {{ ip_list }}
  vars:
    backup_repo: False
    restory_repo: True
    configure_bocloud_repo: False
  roles:
    - role: bocloud_common