---
galaxy_info:
  author: Jorge Quilcate
  description: Install and configure Oracle Weblogic Server.
  company: Sysco AS

  license: MIT

  min_ansible_version: 2.0

  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - middleware
    - oracle
    - web

dependencies: []
