#!/usr/bin/python2
# EASY-INSTALL-ENTRY-SCRIPT: 'docker-compose==1.9.0','console_scripts','docker-compose'
__requires__ = 'docker-compose==1.9.0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('docker-compose==1.9.0', 'console_scripts', 'docker-compose')()
    )
