---
 - name: Host configuration
   hosts: vbox-rac-dc2
   user: vagrant
   become: yes
   roles:
      - common
      - orahost

 - name: ssh configuration
   hosts: vbox-rac-dc2
   user: vagrant
   become: yes
   serial: 1
   roles:
      - {role: orahost-ssh, when: configure_cluster and not old_ssh_config}

 - name: Storage Configuration
   hosts: vbox-rac-dc2
   user: vagrant
   become: yes
   roles:
      - orahost-storage

 - name: Oracle Grid Infrastructure installation
   hosts: vbox-rac-dc2
   user: vagrant
   become: yes
   roles:
      - oraswgi-install

 - name: ASM Configuration, Database Server Installation & Database Creation
   hosts: vbox-rac-dc2
   user: vagrant
   become: yes
   roles:
      - oraasm-createdg
      - oraswdb-install
      - oradb-manage-db

 - name: Install cx_oracle
   hosts: vbox-rac-dc2
   user: vagrant
   become: yes
   roles:
      - cxoracle

 - name: Configure Logrotate
   hosts: vbox-rac-dc2
   user: vagrant
   become: yes
   roles:
      - orahost-logrotate
