- name: Create Related Dockerdd Directory
  file: path={{ DEFAULT_WORKSPACE }}/docker/ state=directory

- name: Copy paas_generalpurpose Container Related File(1/1)
  template: src=paas_generalpurpose.j2 dest={{ DEFAULT_WORKSPACE }}/docker/paas_generalpurpose.sh mode=0755

- name: Start paas_generalpurpose Container Instance
  shell: "{{ DEFAULT_WORKSPACE }}/docker/paas_generalpurpose.sh"
