---
- hosts: DB
  roles:
    - {role: cleanup, tags: [ 'setup' ] }
#   - { role: security, tags: [ 'setup' ] }
    - { role: galera_packages, tags: [ 'setup', 'packages' ] }
    - { role: galera_privs, tags: [ 'auth' ] }
    - { role: galera_conf, tags: [ 'config' ] }
