- name: Create Related Dockerdd Directory
  file: path={{ DEFAULT_WORKSPACE }}/docker/ state=directory

- name: Copy paas_basic_logger Container Related File(1/1)
  template: src=paas_basic_logger.j2 dest={{ DEFAULT_WORKSPACE }}/docker/paas_basic_logger.sh mode=0755

- name: Start paas_basic_logger Container Instance
  shell: "{{ DEFAULT_WORKSPACE }}/docker/paas_basic_logger.sh"
